### ISSUE TITLE
Typescript example?

### ISSUE THREAD

**Issue by jerekarppinen** [mikeborozdin/jest-react-hooks-shallow#10]
Looks good. I am struggling to make the jest import with Typescript though.

**Comment by mikeborozdin** [comment]
Hi @jerekarppinen,

Thanks for opening an issue! What's the exact error message?

I'm using it on a few TypeScript projects and it's been working smoothly so far. And the library does provide TypeScript typing.

**Comment by titenis** [comment]
` error TS2345: Argument of type 'typeof jest' is not assignable to parameter of type 'Jest'.
      Types of property 'mock' are incompatible.
        Type '(moduleName: string, factory?: () => unknown, options?: MockOptions) => typeof jest' is not assignable to type '(module: string, mock: object) => void'.
          Types of parameters 'factory' and 'mock' are incompatible.
            Type 'object' is not assignable to type '() => unknown'.
              Type '{}' provides no match for the signature '(): unknown'.

    14 enableHooks(jest);
`

**Comment by mikeborozdin** [comment]
Hi @jerekarppinen ,

I see what the problem is. I've fixed it in version `1.4.0`, please upgrade.
