### ISSUE TITLE
Facing `Cannot read property 'refs' of undefined` for Tests with enzyme mount wrapper on component having material ui components

### ISSUE THREAD

**Issue by krajasekhar** [mikeborozdin/jest-react-hooks-shallow#11]
After including this library and adding the setup, able to pass tests from`useEffect` actions seamlessly which I couldn't do with other solutions.
But soon, all the other test components (where  `mount` wrapper of enzyme is used and the components are using`material-ui` components) started throwing throwing the error `Cannot read property 'refs' of undefined` error.

Sample Test Component:
```
//TestComponent.js
import React, { useState } from 'react';
import TextField from '@material-ui/core/TextField';

const TestComponent = () => {
  return (
    <TextField value="somedata" />
  }
}
export default TestComponent;

//TestComponent.test.js
import React from 'react';
import { mount } from 'enzyme';
import TestComponent from '../TestComponent';
describe('TestComponent', () => {
        Date.now = jest.fn(() => 123);
	it('matches snapshot', () => {
		const componentWrapper = mount(<TestComponent />);
		expect(componentWrapper).toMatchSnapshot();
	});
});
```
![image](https://user-images.githubusercontent.com/5477450/80274411-c2b66980-86f7-11ea-8c0c-c2e2498d5db1.png)

But, Not getting error when i try using useRef and ForwardRef's inside the component
Not getting error with material-ui components too when I exclude this package from setup..
Any work around for this would be welcomed?

**Comment by mikeborozdin** [comment]
Hi @krajasekhar ,

Thanks you for reporting that! I haven't tested it with `mount()`, but I'll have a look into the problem and will come back to you!

**Comment by mikeborozdin** [comment]
Hi @krajasekhar ,

Please, upgrade to version `1.3.0` and use a combination of `disableHooks()`/`reenableHooks()` when working working with `mount()` [as written here](https://github.com/mikeborozdin/jest-react-hooks-shallow#usage-with-mount)

**Comment by krajasekhar** [comment]
Hi @mikeborozdin ,
Thanks for your work on this. But as per my understanding on the solution provided, why shall I go back and change every test suite (having `mount()`) in the application and put `disableHooks()` , instead I would love to do if I can disable it globally and then enable only at the required test suites/ test cases where I need it (relying on `shallow()` and have `useEffect` kind of hooks in it) since that is place I was having issue at the very beginning.

**Comment by mikeborozdin** [comment]
Hi @krajasekhar ,

Got it and implemented :). Please, upgrade to version `1.4.0` and check [this guide](https://github.com/mikeborozdin/jest-react-hooks-shallow#usage-with-mount).

**Comment by mikeborozdin** [comment]
@krajasekhar,

Is it still an issue? Can I close the ticket?

**Comment by krajasekhar** [comment]
@mikeborozdin - Closing the ticket.
