### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Kisama** [mikeborozdin/jest-react-hooks-shallow#12]
When I test with mount It show "TypeError: Cannot read property '0' of undefined"

I looks length of previousDependencies  and length of currentDependencies can be different.
For example, 
if i have 2 unit tests which first one uses shallow, second one uses mount, 

- first unit test runs previousDependencies is undefined, currentDependencies's length is 3
- second unit test runs  previousDependencies'lengh is 3, currentDependencies is undefined

It throws TypeError: Cannot read property '0' of undefined 

const noDepsOrDifferent = (previousDependencies: unknown[], currentDependencies: unknown[]): boolean => {
  return previousDependencies === undefined ||
    previousDependencies.some((prevDep, index) => prevDep !== currentDependencies[index]);
}

I looks

**Comment by mikeborozdin** [comment]
Hi @Kisama ,

Please, upgrade to version `1.3.0` and use a combination of `disableHooks()`/`reenableHooks()` [as written here](https://github.com/mikeborozdin/jest-react-hooks-shallow#usage-with-mount)

**Comment by mikeborozdin** [comment]
Hi @Kisama ,

There's even a newer version - `1.4.1` with [a better API](https://github.com/mikeborozdin/jest-react-hooks-shallow#usage-with-mount). Can you please check if it solves the problem?

**Comment by Kisama** [comment]
Hi @mikeborozdin 
Thank you for your support. It works well

**Comment by mikeborozdin** [comment]
> Hi @mikeborozdin 
> 
> Thank you for your support. It works well 

Good to know! I’m closing the ticket.

**Comment by phoebedg** [comment]
I am experiencing the same issue - `disableHooks()` resolves it, but `withoutHook()` does not.
