### ISSUE TITLE
Acknowledgement

### ISSUE THREAD

**Issue by davidmfoley** [mikeborozdin/jest-react-hooks-shallow#23]
Just giving credit for the idea/hack of using the function body as the key to figure out which effect call is which here:
https://github.com/mikeborozdin/jest-react-hooks-shallow/blob/c7c079573dd36ffe4776bc4e439e101f6e281245/src/mock-use-effect/mock-use-effect.ts#L20

I borrowed that strategy for this adapter that enables shallow testing of effects at the adapter level: https://github.com/davidmfoley/enzyme-adapter-react-16-with-shallow-effects/blob/master/src/enableEffects.js#L2

Thanks!

**Comment by mikeborozdin** [comment]
Hi @davidmfoley,

Sorry for a late response, I really appreciate your kind words! 

You've got an interesting idea with an Enzyme adapter. What do you think about joining our efforts?
