### ISSUE TITLE
Added plugin to package.json

### ISSUE THREAD

**Issue by Serzhs** [mikeborozdin/jest-react-hooks-shallow#31]
How can I add this option via package.json file jest config?

**Comment by mikeborozdin** [comment]
Hi @Serzhs ,

Apologies for the late response. You do need to have a separate `js` file as per example. If you use `package.json` for configuration Jest, then just add: `"setupFilesAfterEnv": ["path-to-your-setup-jest-file.js"]` to it. And then `path-to-your-setup-jest-file.js` should have:


```js
import enableHooks from 'jest-react-hooks-shallow';

// pass an instance of jest to `enableHooks()`
enableHooks(jest);
```
