### ISSUE TITLE
Function returned from useEffect, testable?

### ISSUE THREAD

**Issue by jg123** [mikeborozdin/jest-react-hooks-shallow#4]
Say you have the following code:
```javascript
  useEffect(() => {
    dispatch(fetchData());
    return () => {
      dispatch(resetPaging());
    };
  }, [dispatch]);
```
Does this package allow you to test if `resetPaging` was called?

**Comment by mikeborozdin** [comment]
Hi @jg123 ,

Not right now. But I'm literally finishing a release that will support that.

**Comment by mikeborozdin** [comment]
@jg123 ,

I've just published a new version that does call cleanup functions. However, there's one limitation - they won't be called on a component unmount. They'll be only called before the same effect gets executed. That's because I don't have access to the component lifecycle from this library.

**Comment by jg123** [comment]
Great! I'll give it a try and report back.
